name: poker

services:
  backend:
    image: ghcr.io/axelrindle/planningpoker/backend:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - backend_data:/data

  frontend:
    image: ghcr.io/axelrindle/planningpoker/frontend:latest
    restart: always
    ports:
      - 3002:8080
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:3000

volumes:
  backend_data:
